import clsx from 'clsx'
import { Bot, ChevronRight, Database, LayoutDashboard, Mail, Sparkles, Workflow } from 'lucide-react'
import type { ReactNode } from 'react'
import type { Kpi } from '../lib/analytics'
import { useData } from '../lib/store'
import { Card, CardHeader, Delta } from './ui'

export function KpiCard({
  label,
  kpi,
  format = 'count',
  goodWhenUp = true,
  neutral,
  share,
  accent,
}: {
  label: string
  kpi: Kpi
  format?: 'count' | 'score'
  goodWhenUp?: boolean
  neutral?: boolean
  share?: number | null
  accent?: string
}) {
  const value = kpi.value == null ? '—' : format === 'score' ? `${kpi.value > 0 ? '+' : ''}${kpi.value.toFixed(2)}` : kpi.value.toLocaleString()
  return (
    <Card className="p-4">
      <p className="flex items-center gap-1.5 text-xs font-medium text-ink-2">
        {accent && <span className="size-2 rounded-full" style={{ background: accent }} />}
        {label}
      </p>
      <p className="mt-2 text-2xl font-semibold tracking-tight text-ink tabular">{value}</p>
      <div className="mt-1 flex items-center gap-2">
        <Delta value={kpi.delta} format={format === 'score' ? 'abs' : 'pct'} goodWhenUp={goodWhenUp} neutral={neutral} />
        {share != null && <span className="text-xs text-ink-3 tabular">{Math.round(share * 100)}% of total</span>}
      </div>
    </Card>
  )
}

export function rangeLabel(preset: string) {
  return preset === '7d' ? 'Last 7 days' : preset === '30d' ? 'Last 30 days' : preset === '90d' ? 'Last 90 days' : 'All time'
}

function timeAgo(iso: string) {
  const s = Math.max(0, (Date.now() - Date.parse(iso)) / 1000)
  if (s < 60) return 'just now'
  if (s < 3600) return `${Math.round(s / 60)} min ago`
  if (s < 86400) return `${Math.round(s / 3600)} h ago`
  return `${Math.round(s / 86400)} d ago`
}

/** Shows the Gmail → n8n → AI → DB → Sentra pipeline and its latest activity. */
export function PipelineStrip({ compact = false }: { compact?: boolean }) {
  const { records } = useData()
  const latest = records[0]
  const steps: { icon: ReactNode; label: string; detail: string }[] = [
    { icon: <Mail size={15} />, label: 'Gmail', detail: 'Feedback intake' },
    { icon: <Workflow size={15} />, label: 'n8n', detail: 'Automation' },
    { icon: <Bot size={15} />, label: 'AI analysis', detail: 'Sentiment · theme · issue' },
    { icon: <Database size={15} />, label: 'Database', detail: `${records.length.toLocaleString()} records` },
    { icon: <LayoutDashboard size={15} />, label: 'Sentra', detail: latest ? `Last record ${timeAgo(latest.created_at)}` : 'Waiting for data' },
  ]
  return (
    <Card className={clsx('overflow-x-auto', compact ? 'px-4 py-3' : 'p-5')}>
      <ol className="flex min-w-max items-center gap-2">
        {steps.map((s, i) => (
          <li key={s.label} className="flex items-center gap-2">
            <div className="flex items-center gap-2.5">
              <span className={clsx('flex size-8 items-center justify-center rounded-lg', i === steps.length - 1 ? 'bg-accent text-white' : 'bg-surface-2 text-ink-2')}>{s.icon}</span>
              <div className="leading-tight">
                <p className="text-sm font-medium text-ink">{s.label}</p>
                <p className="text-xs text-ink-3">{s.detail}</p>
              </div>
            </div>
            {i < steps.length - 1 && <ChevronRight size={16} className="mx-1 text-ink-3" />}
          </li>
        ))}
      </ol>
    </Card>
  )
}

export function ExecutiveSummaryCard({ className }: { className?: string }) {
  const { summary } = useData()
  return (
    <Card className={className}>
      <CardHeader
        title={
          <span className="flex items-center gap-1.5">
            <Sparkles size={15} className="text-accent-text" /> AI executive summary
          </span>
        }
        subtitle={
          summary
            ? summary.origin === 'ai'
              ? `Generated by the AI workflow · ${new Date(summary.generated_at).toLocaleString(undefined, { dateStyle: 'medium', timeStyle: 'short' })}`
              : 'Synthesised from the analyzed feedback in the selected range'
            : undefined
        }
      />
      <div className="px-5 pb-5">
        {summary ? (
          <>
            <p className="text-sm leading-relaxed text-ink">{summary.summary}</p>
            {summary.highlights.length > 0 && (
              <ul className="mt-4 space-y-1.5">
                {summary.highlights.map((h) => (
                  <li key={h} className="flex gap-2 text-sm text-ink-2">
                    <span className="mt-2 size-1.5 shrink-0 rounded-full bg-accent" />
                    {h}
                  </li>
                ))}
              </ul>
            )}
          </>
        ) : (
          <p className="text-sm text-ink-3">A summary will appear once feedback has been analyzed.</p>
        )}
      </div>
    </Card>
  )
}
